### ISSUE TITLE
Catch TypeError: Cannot read property 'structureBlocks' of undefined

### ISSUE THREAD

**Issue by sinitsyn-alex** [DimaRGB/text-mask-addon-iban#6]
Есть некоторые страны, которых может не быть в пакете iban.
Необходимо возвратить false, если страны нет в iban

```
const ibanCountrySpecification = IBAN.countries[country]

if (!ibanCountrySpecification) return false
const bbanBlocks = ibanCountrySpecification.structureBlocks()
```

**Comment by fatihawk** [comment]
+1 same issiue

**Comment by DimaRGB** [comment]
Thank you for your attention, sorry for late, just checked the repo.

Issue fixed: #17 
Version bumped: https://github.com/DimaRGB/text-mask-addon-iban/releases/tag/v0.0.4
